### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by chikkadd** [3scale/3scale_toolbox#135]
getting this error while trying to get the response. Please help to resolve this

**Comment by eguzki** [comment]
https://github.com/3scale/3scale_toolbox/blob/master/docs/ssl_errors.md

In short:
* The recommended way to solve this issues is fetching remote host certificate and using that certificate with the toolbox. 
```bash
SSL_CERT_FILE=self-signed-cert.pem 3scale command params
```
In the documentation you will find ways to download remote host certificate.

* The not recommended way for production environments and useful for *devel* environments: disabling TLS verification. 3scale Toolbox allows insecure connections when specified. For that feature, the toolbox allows `-k/--insecure` flag on any command and the toolbox will proceed and operate even for server connections otherwise considered insecure.
