### ISSUE TITLE
RFE: use it as a tool to migrate from SaaS to OnPremise

### ISSUE THREAD

**Issue by lucamaf** [3scale/3scale_toolbox#167]
This is a recurring requirement from customer, to be able to migrate from SaaS to OnPrem or vice-versa.
It would be nice if there was a command that migrated the whole Service, including Applications and Policies.

**Comment by lucamaf** [comment]
of course statistics, history and cached keys will be lost in the migration

**Comment by eguzki** [comment]
Everything in a single command could be done. There are copy commands for some 3scale components, though.

* Services can be [copied](https://github.com/3scale/3scale_toolbox/blob/master/docs/copy-service.md) one by one:
```
3scale service copy [opts] -s <src> -d <dst> <source-service>
```
The command include application plans when copying services.

* Policy Registry can also be [copied](https://github.com/3scale/3scale_toolbox/blob/master/docs/copy-policy-registry.md):
```
3scale policy-registry copy [opts] <source_remote> <target_remote>
```

* Application plans can be [exported and imported](https://github.com/3scale/3scale_toolbox/blob/master/docs/export-import-app-plan.md) individually.
```
3scale application-plan export [opts] <remote> <service_system_name> <plan_system_name>

3scale application-plan import [opts] <remote> <service_system_name>
```
* Accounts

There is no *copy* command for that, as it does not seem to make sense. Rise your hand if you think otherwise.

* Applications

Applications relate accounts with services (via application plan). There is no *copy* command for that, as it does not seem to make sense for accounts. Rise your hand if you think otherwise.

**Comment by lucamaf** [comment]
at the moment I don't see the need to copy Accounts or Applications over and I believe Application plans are now copied as part of the Service copy.
One additional requirement that recently came up when dealing with air-gapped environments is the possibility to have an artifact produced by the first part of the command (export like) and then usable for the create/import phase of the command. Would I need to add a separate PR for this?

**Comment by eguzki** [comment]
The product export/import command produces an artifact (yaml file) that can be copied over and imported. Would that work for your use case? https://github.com/3scale/3scale_toolbox/blob/main/docs/export-import-product.md

**Comment by lucamaf** [comment]
that works nicely for the purpose
