### ISSUE TITLE
Integration Test Failures on RHEL78 (x86_64 arch)

### ISSUE THREAD

**Issue by krishvoor** [3scale/3scale_toolbox#294]
Hi Team,

Thanks for the awesome readme/tutorials on 3scale_toolbox. I could build 3scale_toolbox from the source & run the unit tests without any issue. However, we observed failures during Integration tests, where-in we populated `.env` file with required details, please find below log file for further details on the errors.

To understand better, the environment setup, we looked at one of the jobs in [CircleCi](https://app.circleci.com/pipelines/github/3scale/3scale_toolbox/789/workflows/10c4b7c[…]4ab9-9857-36ae0ee9ea72/jobs/2589/parallel-runs/0/steps/0-106).
However, we did not see any deviations in the enclosed logs, whatsoever - we would like to seek some expertise and understand if the set of errors we are seeing is something simple, if so, what can we do ?
[x86_64_rhel78_ruby27.log](https://github.com/3scale/3scale_toolbox/files/6320046/x86_64_rhel78_ruby27.log)

**Comment by eguzki** [comment]
From the logs I see `Net::HTTPForbidden 403 Forbidden` when you try to create a service. It could be that the tenant (admin account) does not have permissions to add more services. The integration tests create services and then delete them when done. Make sure you can create new services manually from the dashboard. If that is the issue, you will need to request to enable multiple services for your tenant from the master account.

I can also see `Net::HTTPBadGateway 502 Bad Gateway` errors when trying to list tenant's activedocs. Since it is a 5XX error, I cannot tell without checking 3scale pods logs to see what is going on behind the scene. 

I propose to check first ForbiddenErrors and then face the 5xx issues.  

Check it out about the multiple services and come back to us

**Comment by krishvoor** [comment]
Thanks for your response @eguzki
Currently, what I have is a 90 day trial period developer's account.
And we are running these tests currently on Virtual Machine and not inside pods.

> The integration tests create services and then delete them when done. Make sure you can create new services manually from the dashboard. If that is the issue, you will need to request to enable multiple services for your tenant from the master account.

So, given that, this is a 90-day trial account, I cannot seem to create "additional" services.
I am not sure about, how to proceed next i.e. 

> If that is the issue, you will need to request to enable multiple services for your tenant from the master account.

**Comment by eguzki** [comment]
Developer account? you need the admin account of a tenant (aka 3scale provider account) to run the integration tests.

**Comment by krishvoor** [comment]
Thanks for the pointers @eguzki  - the job now works across both ppc64le as well x86_64 as well.
Closing this issue.
